//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TanjiMimic.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Data : global::System.Configuration.ApplicationSettingsBase {
        
        private static Data defaultInstance = ((Data)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Data())));
        
        public static Data Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection BlackListTxt {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BlackListTxt"]));
            }
            set {
                this["BlackListTxt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("85")]
        public ushort PlayerDataLoaded {
            get {
                return ((ushort)(this["PlayerDataLoaded"]));
            }
            set {
                this["PlayerDataLoaded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1988")]
        public ushort PlayerGesture {
            get {
                return ((ushort)(this["PlayerGesture"]));
            }
            set {
                this["PlayerGesture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1270")]
        public ushort PlayerDance {
            get {
                return ((ushort)(this["PlayerDance"]));
            }
            set {
                this["PlayerDance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1836")]
        public ushort PlayerSay {
            get {
                return ((ushort)(this["PlayerSay"]));
            }
            set {
                this["PlayerSay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3449")]
        public ushort PlayerShout {
            get {
                return ((ushort)(this["PlayerShout"]));
            }
            set {
                this["PlayerShout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("279")]
        public ushort PlayerSign {
            get {
                return ((ushort)(this["PlayerSign"]));
            }
            set {
                this["PlayerSign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2421")]
        public ushort PlayerSendMessage {
            get {
                return ((ushort)(this["PlayerSendMessage"]));
            }
            set {
                this["PlayerSendMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort PlayerWhisper {
            get {
                return ((ushort)(this["PlayerWhisper"]));
            }
            set {
                this["PlayerWhisper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1583")]
        public ushort PlayerChangeData {
            get {
                return ((ushort)(this["PlayerChangeData"]));
            }
            set {
                this["PlayerChangeData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort PlayerActionsDetected {
            get {
                return ((ushort)(this["PlayerActionsDetected"]));
            }
            set {
                this["PlayerActionsDetected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1114")]
        public ushort HostGesture {
            get {
                return ((ushort)(this["HostGesture"]));
            }
            set {
                this["HostGesture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1413")]
        public ushort HostDance {
            get {
                return ((ushort)(this["HostDance"]));
            }
            set {
                this["HostDance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3331")]
        public ushort HostSay {
            get {
                return ((ushort)(this["HostSay"]));
            }
            set {
                this["HostSay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3221")]
        public ushort HostShout {
            get {
                return ((ushort)(this["HostShout"]));
            }
            set {
                this["HostShout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("215")]
        public ushort HostSign {
            get {
                return ((ushort)(this["HostSign"]));
            }
            set {
                this["HostSign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2085")]
        public ushort HostSendMessage {
            get {
                return ((ushort)(this["HostSendMessage"]));
            }
            set {
                this["HostSendMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2274")]
        public ushort HostChangeClothes {
            get {
                return ((ushort)(this["HostChangeClothes"]));
            }
            set {
                this["HostChangeClothes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1350")]
        public ushort HostChangeMotto {
            get {
                return ((ushort)(this["HostChangeMotto"]));
            }
            set {
                this["HostChangeMotto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort HostWhisper {
            get {
                return ((ushort)(this["HostWhisper"]));
            }
            set {
                this["HostWhisper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort Setting {
            get {
                return ((ushort)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
    }
}
