//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TanjiMimic.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Data : global::System.Configuration.ApplicationSettingsBase {
        
        private static Data defaultInstance = ((Data)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Data())));
        
        public static Data Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection BlackListTxt {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BlackListTxt"]));
            }
            set {
                this["BlackListTxt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("961")]
        public ushort PlayerDataLoaded {
            get {
                return ((ushort)(this["PlayerDataLoaded"]));
            }
            set {
                this["PlayerDataLoaded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2482")]
        public ushort PlayerGesture {
            get {
                return ((ushort)(this["PlayerGesture"]));
            }
            set {
                this["PlayerGesture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3848")]
        public ushort PlayerDance {
            get {
                return ((ushort)(this["PlayerDance"]));
            }
            set {
                this["PlayerDance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2735")]
        public ushort PlayerSay {
            get {
                return ((ushort)(this["PlayerSay"]));
            }
            set {
                this["PlayerSay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3274")]
        public ushort PlayerShout {
            get {
                return ((ushort)(this["PlayerShout"]));
            }
            set {
                this["PlayerShout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2566")]
        public ushort PlayerSign {
            get {
                return ((ushort)(this["PlayerSign"]));
            }
            set {
                this["PlayerSign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("625")]
        public ushort PlayerSendMessage {
            get {
                return ((ushort)(this["PlayerSendMessage"]));
            }
            set {
                this["PlayerSendMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public ushort HostGesture {
            get {
                return ((ushort)(this["HostGesture"]));
            }
            set {
                this["HostGesture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1764")]
        public ushort HostDance {
            get {
                return ((ushort)(this["HostDance"]));
            }
            set {
                this["HostDance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2462")]
        public ushort HostSay {
            get {
                return ((ushort)(this["HostSay"]));
            }
            set {
                this["HostSay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1559")]
        public ushort HostShout {
            get {
                return ((ushort)(this["HostShout"]));
            }
            set {
                this["HostShout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1037")]
        public ushort HostSign {
            get {
                return ((ushort)(this["HostSign"]));
            }
            set {
                this["HostSign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2046")]
        public ushort HostSendMessage {
            get {
                return ((ushort)(this["HostSendMessage"]));
            }
            set {
                this["HostSendMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2889")]
        public ushort HostChangeClothes {
            get {
                return ((ushort)(this["HostChangeClothes"]));
            }
            set {
                this["HostChangeClothes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3060")]
        public ushort HostChangeMotto {
            get {
                return ((ushort)(this["HostChangeMotto"]));
            }
            set {
                this["HostChangeMotto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English")]
        public string SavedLang {
            get {
                return ((string)(this["SavedLang"]));
            }
            set {
                this["SavedLang"] = value;
            }
        }
    }
}
